---
- name: Setup MySQL Database
  hosts: db
  become: yes
  vars:
    db_name: example_app
    user_name: example-app
    user_password: P@ssw0rd
  tasks:
    - name: Install packages
      package:
        name:
          - mysql-server
          - python3-pip
        state: present

    - name: Start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Install MySQL Python client
      pip:
        name: PyMySQL

    - name: Create database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: ""
        login_host: localhost
        login_unix_socket: "/var/run/mysqld/mysqld.sock"

    - name: Create a database user
      mysql_user:
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        priv: "{{ db_name }}.*:ALL"
        login_user: root
        login_password: ""
        login_host: localhost
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
